export type ReceiptLine = { name: string; quantity: number; unitPrice: string; discount: number };
export type ReceiptInput = { invoiceNo: string; mode: "sale" | "purchase"; lines: ReceiptLine[]; total: number; paid: number };
const LAST_RECEIPT = "hawr-last-receipt-v1";

export function buildReceiptHtml(input: ReceiptInput) {
  const title = input.mode === "sale" ? "إيصال بيع" : "إيصال شراء";
  const rows = input.lines.map(line => `<tr><td>${line.name}</td><td>${line.quantity}</td><td>${Number(line.unitPrice).toLocaleString("ar-EG")}</td><td>${Math.max(0, Number(line.unitPrice) * line.quantity - line.discount).toLocaleString("ar-EG")}</td></tr>`).join("");
  return `<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${title} ${input.invoiceNo}</title><style>@page{size:80mm auto;margin:0}*{box-sizing:border-box}body{width:72mm;margin:0 auto;padding:4mm 0;font-family:Arial,sans-serif;color:#000;font-size:12px}h1{text-align:center;font-size:18px;margin:0 0 3mm}p{margin:1.5mm 0;text-align:center}.line{border-top:1px dashed #000;margin:3mm 0}table{width:100%;border-collapse:collapse;font-size:10px}th,td{padding:1.5mm 0;text-align:right;border-bottom:1px solid #ddd}th:last-child,td:last-child{text-align:left}.total{font-weight:bold;font-size:15px;display:flex;justify-content:space-between;margin-top:3mm}</style></head><body><h1>معرض حور للأدوات المنزلية</h1><p>${title}</p><p>رقم الفاتورة: ${input.invoiceNo}</p><p>${new Date().toLocaleString("ar-EG")}</p><div class="line"></div><table><thead><tr><th>الصنف</th><th>كم</th><th>السعر</th><th>الإجمالي</th></tr></thead><tbody>${rows}</tbody></table><div class="line"></div><div class="total"><span>الإجمالي</span><span>${input.total.toLocaleString("ar-EG")} ج.م</span></div><div class="total"><span>المدفوع</span><span>${input.paid.toLocaleString("ar-EG")} ج.م</span></div><div class="total"><span>المتبقي</span><span>${Math.max(0, input.total - input.paid).toLocaleString("ar-EG")} ج.م</span></div><p style="margin-top:7mm">شكرًا لتعاملكم معنا</p><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script></body></html>`;
}

export function saveLastReceipt(input: ReceiptInput) { if (typeof localStorage !== "undefined") localStorage.setItem(LAST_RECEIPT, JSON.stringify(input)); }
export function getLastReceipt(): ReceiptInput | null { if (typeof localStorage === "undefined") return null; try { return JSON.parse(localStorage.getItem(LAST_RECEIPT) || "null") as ReceiptInput | null; } catch { return null; } }
export function printReceipt80mm(input: ReceiptInput) { const popup = window.open("", "_blank", "width=420,height=720"); if (!popup) return false; popup.document.write(buildReceiptHtml(input)); popup.document.close(); return true; }
export function printLastReceipt() { const receipt = getLastReceipt(); return receipt ? printReceipt80mm(receipt) : false; }
