import { and, eq, desc, gte, lte, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, categories, products, customers, suppliers, expenses, syncOperations, sales, saleItems, purchases, inventoryMovements, installments, installmentPayments, purchaseItems } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { purchaseRemovalDelta, purchaseStockDelta } from "../shared/purchaseFlow";

let _db: ReturnType<typeof drizzle> | null = null;
const insertIdOf = (result: any) => Number(result?.insertId ?? result?.[0]?.insertId ?? 0);
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {};
  for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }
  if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; }
  if (user.role !== undefined || user.openId === ENV.ownerOpenId) { values.role = user.role ?? "admin"; updateSet.role = values.role; }
  values.lastSignedIn ??= new Date(); if (!Object.keys(updateSet).length) updateSet.lastSignedIn = new Date();
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listCategories() { const db = await getDb(); return db ? db.select().from(categories).orderBy(desc(categories.createdAt)) : []; }
export async function createCategory(name: string) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.insert(categories).values({ name }); return { success: true }; }
export async function updateCategory(id: number, name: string) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.update(categories).set({ name }).where(eq(categories.id, id)); return { success: true }; }
export async function deleteCategory(id: number) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.delete(categories).where(eq(categories.id, id)); return { success: true }; }
export async function listProducts() { const db = await getDb(); return db ? db.select().from(products).orderBy(desc(products.createdAt)) : []; }
export async function listInventoryMovements() { const db = await getDb(); return db ? db.select().from(inventoryMovements).orderBy(desc(inventoryMovements.createdAt)) : []; }
export async function listInstallments() { const db = await getDb(); return db ? db.select().from(installments).orderBy(desc(installments.dueDate)) : []; }
export async function adjustInventory(input: { productId: number; quantity: number; note?: string }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.transaction(async tx => { await tx.update(products).set({ stockQty: sql`${products.stockQty} + ${input.quantity}` }).where(eq(products.id, input.productId)); await tx.insert(inventoryMovements).values({ productId: input.productId, type: "adjustment", quantity: input.quantity, note: input.note }); return { success: true }; }); }
export async function listCustomers() { const db = await getDb(); return db ? db.select().from(customers).orderBy(desc(customers.createdAt)) : []; }
export async function listSuppliers() { const db = await getDb(); return db ? db.select().from(suppliers).orderBy(desc(suppliers.createdAt)) : []; }
export async function listExpenses() { const db = await getDb(); return db ? db.select().from(expenses).orderBy(desc(expenses.createdAt)) : []; }
export async function listPurchaseItems() { const db = await getDb(); return db ? db.select({ id: purchaseItems.id, purchaseId: purchaseItems.purchaseId, invoiceNo: purchases.invoiceNo, productId: purchaseItems.productId, productName: purchaseItems.productName, sku: purchaseItems.sku, unit: purchaseItems.unit, quantity: purchaseItems.quantity, unitPrice: purchaseItems.unitPrice, total: purchaseItems.total, createdAt: purchases.createdAt }).from(purchaseItems).innerJoin(purchases, eq(purchaseItems.purchaseId, purchases.id)).orderBy(desc(purchases.createdAt)) : []; }
export async function updatePurchaseItem(id: number, input: { quantity: number; unitPrice: string }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.transaction(async tx => { const [item] = await tx.select().from(purchaseItems).where(eq(purchaseItems.id, id)).limit(1); if (!item) throw new Error("حركة التوريد غير موجودة أو تم حذفها مسبقًا"); const delta = purchaseStockDelta(item.quantity, input.quantity); if (delta < 0 && item.quantity - input.quantity > 0) { const [product] = await tx.select().from(products).where(eq(products.id, item.productId)).limit(1); if (!product || product.stockQty < -delta) throw new Error("الكمية الحالية في المخزون لا تسمح بالتعديل"); } await tx.update(products).set({ stockQty: sql`${products.stockQty} + ${delta}` }).where(eq(products.id, item.productId)); await tx.update(purchaseItems).set({ quantity: input.quantity, unitPrice: input.unitPrice, total: (input.quantity * Number(input.unitPrice)).toFixed(2) }).where(eq(purchaseItems.id, id)); await tx.insert(inventoryMovements).values({ productId: item.productId, type: "adjustment", quantity: delta, referenceId: item.purchaseId, note: `تعديل حركة توريد ${id}` }); return { success: true }; }); }
export async function deletePurchaseItem(id: number) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.transaction(async tx => { const [item] = await tx.select().from(purchaseItems).where(eq(purchaseItems.id, id)).limit(1); if (!item) throw new Error("حركة التوريد غير موجودة أو تم حذفها مسبقًا"); const [product] = await tx.select().from(products).where(eq(products.id, item.productId)).limit(1); if (!product || product.stockQty < item.quantity) throw new Error("الكمية الحالية في المخزون لا تسمح بالحذف"); await tx.update(products).set({ stockQty: sql`${products.stockQty} - ${item.quantity}` }).where(eq(products.id, item.productId)); await tx.delete(purchaseItems).where(eq(purchaseItems.id, id)); await tx.insert(inventoryMovements).values({ productId: item.productId, type: "adjustment", quantity: purchaseRemovalDelta(item.quantity), referenceId: item.purchaseId, note: `حذف حركة توريد ${id}` }); return { success: true }; }); }
export async function createProduct(input: { name: string; sku: string; barcode?: string; unit?: string; salePrice: string; costPrice?: string; stockQty?: number; minStock?: number; categoryId?: number }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.insert(products).values(input).then((result: any) => ({ success: true, id: insertIdOf(result) })); }
export async function createCustomer(input: { name: string; phone?: string; address?: string }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.insert(customers).values(input).then(() => ({ success: true })); }
export async function createSupplier(input: { name: string; phone?: string }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.insert(suppliers).values(input).then(() => ({ success: true })); }
export async function createExpense(input: { title: string; category: string; amount: string; notes?: string }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.insert(expenses).values(input).then(() => ({ success: true })); }
export async function updateProduct(id: number, input: Partial<{ name: string; sku: string; barcode: string; unit: string; salePrice: string; costPrice: string; stockQty: number; minStock: number; categoryId: number }>) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.update(products).set(input).where(eq(products.id, id)); return { success: true }; }
export async function deleteProduct(id: number) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.update(products).set({ isActive: false }).where(eq(products.id, id)); return { success: true }; }
export async function updateCustomer(id: number, input: Partial<{ name: string; phone: string; address: string }>) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.update(customers).set(input).where(eq(customers.id, id)); return { success: true }; }
export async function deleteCustomer(id: number) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.delete(customers).where(eq(customers.id, id)); return { success: true }; }
export async function updateSupplier(id: number, input: Partial<{ name: string; phone: string }>) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.update(suppliers).set(input).where(eq(suppliers.id, id)); return { success: true }; }
export async function deleteSupplier(id: number) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.delete(suppliers).where(eq(suppliers.id, id)); return { success: true }; }
export async function deleteExpense(id: number) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); await db.delete(expenses).where(eq(expenses.id, id)); return { success: true }; }
export async function recordSyncOperations(operations: { id: string; type: string; payload: unknown; createdAt: number }[]) { const db = await getDb(); if (!db || !operations.length) return 0; for (const operation of operations) { await db.insert(syncOperations).values({ operationId: operation.id, operationType: operation.type, payload: JSON.stringify(operation.payload), createdAt: new Date(operation.createdAt), syncedAt: new Date() }).onDuplicateKeyUpdate({ set: { syncedAt: new Date() } }); } return operations.length; }
export async function getReportSummary(filters: { from?: Date; to?: Date; sellerId?: number } = {}) { const db = await getDb(); if (!db) return null; const saleWhere = [filters.from ? gte(sales.createdAt, filters.from) : undefined, filters.to ? lte(sales.createdAt, filters.to) : undefined, filters.sellerId ? eq(sales.sellerId, filters.sellerId) : undefined].filter(Boolean) as any[]; const expenseWhere = [filters.from ? gte(expenses.createdAt, filters.from) : undefined, filters.to ? lte(expenses.createdAt, filters.to) : undefined].filter(Boolean) as any[]; const [salesTotal] = await db.select({ value: sql`COALESCE(SUM(${sales.subtotal}), 0)` }).from(sales).where(saleWhere.length ? and(...saleWhere) : undefined); const [expensesTotal] = await db.select({ value: sql`COALESCE(SUM(${expenses.amount}), 0)` }).from(expenses).where(expenseWhere.length ? and(...expenseWhere) : undefined); const [stockValue] = await db.select({ value: sql`COALESCE(SUM(${products.stockQty} * ${products.costPrice}), 0)` }).from(products); const [installmentsDue] = await db.select({ value: sql`COALESCE(SUM(${installments.amount} - ${installments.paidAmount}), 0)` }).from(installments).where(sql`${installments.status} <> 'paid'`); return { sales: Number(salesTotal?.value ?? 0), expenses: Number(expensesTotal?.value ?? 0), profit: Number(salesTotal?.value ?? 0) - Number(expensesTotal?.value ?? 0), stockValue: Number(stockValue?.value ?? 0), installmentsDue: Number(installmentsDue?.value ?? 0) }; }
export async function createSale(input: { invoiceNo: string; customerId?: number; sellerId?: number; paidAmount: string; paymentMethod: "cash" | "card" | "transfer" | "installment"; items: { productId: number; quantity: number; unitPrice: string }[] }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); const total = input.items.reduce((sum, item) => sum + Number(item.unitPrice) * item.quantity, 0); const status = Number(input.paidAmount) >= total ? "paid" : Number(input.paidAmount) > 0 ? "partial" : "unpaid"; return db.transaction(async tx => { for (const item of input.items) { const [product] = await tx.select().from(products).where(eq(products.id, item.productId)).limit(1); if (!product || product.stockQty < item.quantity) throw new Error("الكمية المطلوبة أكبر من الرصيد المتاح في المخزون"); } const result = await tx.insert(sales).values({ invoiceNo: input.invoiceNo, customerId: input.customerId, sellerId: input.sellerId, subtotal: total.toFixed(2), paidAmount: input.paidAmount, paymentMethod: input.paymentMethod, status }); const saleId = insertIdOf(result); for (const item of input.items) { await tx.insert(saleItems).values({ saleId, productId: item.productId, quantity: item.quantity, unitPrice: item.unitPrice }); await tx.update(products).set({ stockQty: sql`${products.stockQty} - ${item.quantity}` }).where(eq(products.id, item.productId)); await tx.insert(inventoryMovements).values({ productId: item.productId, type: "sale", quantity: -item.quantity, referenceId: saleId, note: `فاتورة بيع ${input.invoiceNo}` }); } if (input.paymentMethod === "installment" && input.customerId && total > Number(input.paidAmount)) { await tx.insert(installments).values({ saleId, customerId: input.customerId, dueDate: new Date(Date.now() + 30 * 86400000), amount: (total - Number(input.paidAmount)).toFixed(2), paidAmount: "0", status: "pending" }); } return { saleId, total: total.toFixed(2), status }; }); }
export async function createPurchase(input: { invoiceNo: string; supplierId?: number; paidAmount: string; items: { productId?: number; quantity: number; unitPrice: string; product?: { name: string; sku: string; barcode?: string; unit?: string; salePrice?: string; minStock?: number } }[] }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); const total = input.items.reduce((sum, item) => sum + Number(item.unitPrice) * item.quantity, 0); return db.transaction(async tx => { const result = await tx.insert(purchases).values({ invoiceNo: input.invoiceNo, supplierId: input.supplierId, total: total.toFixed(2), paidAmount: input.paidAmount }); const purchaseId = insertIdOf(result); for (const item of input.items) { let productId = item.productId; let product: any = productId ? (await tx.select().from(products).where(eq(products.id, productId)).limit(1))[0] : undefined; if (!product && item.product) { product = (await tx.select().from(products).where(eq(products.sku, item.product.sku)).limit(1))[0]; if (!product && item.product.barcode) product = (await tx.select().from(products).where(eq(products.barcode, item.product.barcode)).limit(1))[0]; productId = product?.id; } if (!product && item.product) { const created = await tx.insert(products).values({ name: item.product.name, sku: item.product.sku, barcode: item.product.barcode, unit: item.product.unit || "قطعة", salePrice: item.product.salePrice || item.unitPrice, costPrice: item.unitPrice, stockQty: item.quantity, minStock: item.product.minStock || 0 }); productId = insertIdOf(created); product = { id: productId, name: item.product.name, sku: item.product.sku, unit: item.product.unit || "قطعة", stockQty: item.quantity } as typeof product; } else if (product && productId) { await tx.update(products).set({ stockQty: sql`${products.stockQty} + ${item.quantity}`, costPrice: item.unitPrice }).where(eq(products.id, productId)); } if (!productId || !product) throw new Error("بيانات الصنف مطلوبة لإتمام التوريد"); await tx.insert(purchaseItems).values({ purchaseId, productId, productName: product.name, sku: product.sku, unit: product.unit || "قطعة", quantity: item.quantity, unitPrice: item.unitPrice, total: (Number(item.unitPrice) * item.quantity).toFixed(2) }); await tx.insert(inventoryMovements).values({ productId, type: "purchase", quantity: item.quantity, referenceId: purchaseId, note: `فاتورة شراء ${input.invoiceNo}` }); } return { purchaseId, total: total.toFixed(2) }; }); }
export async function recordInstallmentPayment(input: { installmentId: number; amount: string; paymentMethod: "cash" | "card" | "transfer"; note?: string }) { const db = await getDb(); if (!db) throw new Error("تعذر الاتصال بقاعدة البيانات، تحقق من الاتصال ثم أعد المحاولة"); return db.transaction(async tx => { await tx.insert(installmentPayments).values(input); const [installment] = await tx.select().from(installments).where(eq(installments.id, input.installmentId)).limit(1); if (!installment) throw new Error("Installment not found"); const paid = Number(installment.paidAmount) + Number(input.amount); const status = paid >= Number(installment.amount) ? "paid" : "partial"; await tx.update(installments).set({ paidAmount: paid.toFixed(2), status }).where(eq(installments.id, input.installmentId)); return { paidAmount: paid.toFixed(2), status }; }); }
