import { eq, desc, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, categories, products, customers, suppliers, expenses, syncOperations, sales, saleItems, purchases, inventoryMovements, installments, installmentPayments } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {};
  for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }
  if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; }
  if (user.role !== undefined || user.openId === ENV.ownerOpenId) { values.role = user.role ?? "admin"; updateSet.role = values.role; }
  values.lastSignedIn ??= new Date(); if (!Object.keys(updateSet).length) updateSet.lastSignedIn = new Date();
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listCategories() { const db = await getDb(); return db ? db.select().from(categories).orderBy(desc(categories.createdAt)) : []; }
export async function createCategory(name: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(categories).values({ name }); return { success: true }; }
export async function updateCategory(id: number, name: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(categories).set({ name }).where(eq(categories.id, id)); return { success: true }; }
export async function deleteCategory(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(categories).where(eq(categories.id, id)); return { success: true }; }
export async function listProducts() { const db = await getDb(); return db ? db.select().from(products).orderBy(desc(products.createdAt)) : []; }
export async function listInventoryMovements() { const db = await getDb(); return db ? db.select().from(inventoryMovements).orderBy(desc(inventoryMovements.createdAt)) : []; }
export async function listInstallments() { const db = await getDb(); return db ? db.select().from(installments).orderBy(desc(installments.dueDate)) : []; }
export async function adjustInventory(input: { productId: number; quantity: number; note?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.transaction(async tx => { await tx.update(products).set({ stockQty: sql`${products.stockQty} + ${input.quantity}` }).where(eq(products.id, input.productId)); await tx.insert(inventoryMovements).values({ productId: input.productId, type: "adjustment", quantity: input.quantity, note: input.note }); return { success: true }; }); }
export async function listCustomers() { const db = await getDb(); return db ? db.select().from(customers).orderBy(desc(customers.createdAt)) : []; }
export async function listSuppliers() { const db = await getDb(); return db ? db.select().from(suppliers).orderBy(desc(suppliers.createdAt)) : []; }
export async function listExpenses() { const db = await getDb(); return db ? db.select().from(expenses).orderBy(desc(expenses.createdAt)) : []; }
export async function createProduct(input: { name: string; sku: string; barcode?: string; salePrice: string; costPrice?: string; stockQty?: number; minStock?: number; categoryId?: number }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.insert(products).values(input).then(() => ({ success: true })); }
export async function createCustomer(input: { name: string; phone?: string; address?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.insert(customers).values(input).then(() => ({ success: true })); }
export async function createSupplier(input: { name: string; phone?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.insert(suppliers).values(input).then(() => ({ success: true })); }
export async function createExpense(input: { title: string; category: string; amount: string; notes?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.insert(expenses).values(input).then(() => ({ success: true })); }
export async function updateProduct(id: number, input: Partial<{ name: string; sku: string; barcode: string; salePrice: string; costPrice: string; stockQty: number; minStock: number; categoryId: number }>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(products).set(input).where(eq(products.id, id)); return { success: true }; }
export async function deleteProduct(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(products).set({ isActive: false }).where(eq(products.id, id)); return { success: true }; }
export async function updateCustomer(id: number, input: Partial<{ name: string; phone: string; address: string }>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(customers).set(input).where(eq(customers.id, id)); return { success: true }; }
export async function deleteCustomer(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(customers).where(eq(customers.id, id)); return { success: true }; }
export async function updateSupplier(id: number, input: Partial<{ name: string; phone: string }>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(suppliers).set(input).where(eq(suppliers.id, id)); return { success: true }; }
export async function deleteSupplier(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(suppliers).where(eq(suppliers.id, id)); return { success: true }; }
export async function deleteExpense(id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(expenses).where(eq(expenses.id, id)); return { success: true }; }
export async function recordSyncOperations(operations: { id: string; type: string; payload: unknown; createdAt: number }[]) { const db = await getDb(); if (!db || !operations.length) return 0; for (const operation of operations) { await db.insert(syncOperations).values({ operationId: operation.id, operationType: operation.type, payload: JSON.stringify(operation.payload), createdAt: new Date(operation.createdAt), syncedAt: new Date() }).onDuplicateKeyUpdate({ set: { syncedAt: new Date() } }); } return operations.length; }
export async function getReportSummary() { const db = await getDb(); if (!db) return null; const [salesTotal] = await db.select({ value: sql`COALESCE(SUM(${sales.subtotal}), 0)` }).from(sales); const [expensesTotal] = await db.select({ value: sql`COALESCE(SUM(${expenses.amount}), 0)` }).from(expenses); const [stockValue] = await db.select({ value: sql`COALESCE(SUM(${products.stockQty} * ${products.costPrice}), 0)` }).from(products); const [installmentsDue] = await db.select({ value: sql`COALESCE(SUM(${installments.amount} - ${installments.paidAmount}), 0)` }).from(installments).where(sql`${installments.status} <> 'paid'`); return { sales: Number(salesTotal?.value ?? 0), expenses: Number(expensesTotal?.value ?? 0), profit: Number(salesTotal?.value ?? 0) - Number(expensesTotal?.value ?? 0), stockValue: Number(stockValue?.value ?? 0), installmentsDue: Number(installmentsDue?.value ?? 0) }; }
export async function createSale(input: { invoiceNo: string; customerId?: number; paidAmount: string; paymentMethod: "cash" | "card" | "transfer" | "installment"; items: { productId: number; quantity: number; unitPrice: string }[] }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const total = input.items.reduce((sum, item) => sum + Number(item.unitPrice) * item.quantity, 0); const status = Number(input.paidAmount) >= total ? "paid" : Number(input.paidAmount) > 0 ? "partial" : "unpaid"; return db.transaction(async tx => { for (const item of input.items) { const [product] = await tx.select().from(products).where(eq(products.id, item.productId)).limit(1); if (!product || product.stockQty < item.quantity) throw new Error("Insufficient stock"); } const result = await tx.insert(sales).values({ invoiceNo: input.invoiceNo, customerId: input.customerId, subtotal: total.toFixed(2), paidAmount: input.paidAmount, paymentMethod: input.paymentMethod, status }); const saleId = Number((result as any)[0]?.insertId ?? 0); for (const item of input.items) { await tx.insert(saleItems).values({ saleId, productId: item.productId, quantity: item.quantity, unitPrice: item.unitPrice }); await tx.update(products).set({ stockQty: sql`${products.stockQty} - ${item.quantity}` }).where(eq(products.id, item.productId)); await tx.insert(inventoryMovements).values({ productId: item.productId, type: "sale", quantity: -item.quantity, referenceId: saleId, note: `فاتورة بيع ${input.invoiceNo}` }); } if (input.paymentMethod === "installment" && input.customerId && total > Number(input.paidAmount)) { await tx.insert(installments).values({ saleId, customerId: input.customerId, dueDate: new Date(Date.now() + 30 * 86400000), amount: (total - Number(input.paidAmount)).toFixed(2), paidAmount: "0", status: "pending" }); } return { saleId, total: total.toFixed(2), status }; }); }
export async function createPurchase(input: { invoiceNo: string; supplierId?: number; paidAmount: string; items: { productId: number; quantity: number; unitPrice: string }[] }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const total = input.items.reduce((sum, item) => sum + Number(item.unitPrice) * item.quantity, 0); return db.transaction(async tx => { const result = await tx.insert(purchases).values({ invoiceNo: input.invoiceNo, supplierId: input.supplierId, total: total.toFixed(2), paidAmount: input.paidAmount }); const purchaseId = Number((result as any)[0]?.insertId ?? 0); for (const item of input.items) { await tx.update(products).set({ stockQty: sql`${products.stockQty} + ${item.quantity}` }).where(eq(products.id, item.productId)); await tx.insert(inventoryMovements).values({ productId: item.productId, type: "purchase", quantity: item.quantity, referenceId: purchaseId, note: `فاتورة شراء ${input.invoiceNo}` }); } return { purchaseId, total: total.toFixed(2) }; }); }
export async function recordInstallmentPayment(input: { installmentId: number; amount: string; paymentMethod: "cash" | "card" | "transfer"; note?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); return db.transaction(async tx => { await tx.insert(installmentPayments).values(input); const [installment] = await tx.select().from(installments).where(eq(installments.id, input.installmentId)).limit(1); if (!installment) throw new Error("Installment not found"); const paid = Number(installment.paidAmount) + Number(input.amount); const status = paid >= Number(installment.amount) ? "paid" : "partial"; await tx.update(installments).set({ paidAmount: paid.toFixed(2), status }).where(eq(installments.id, input.installmentId)); return { paidAmount: paid.toFixed(2), status }; }); }
