import * as mysqlDb from "./db.mysql";
import * as localDb from "./db.local";

const useLocalDatabase = process.env.LOCAL_DESKTOP_MODE === "1" || Boolean(process.env.LOCAL_DB_PATH);
const implementation: Record<string, any> = useLocalDatabase ? localDb : mysqlDb;

export const getDb = implementation.getDb;
export const upsertUser = implementation.upsertUser;
export const getUserByOpenId = implementation.getUserByOpenId;
export const listEmployees = implementation.listEmployees;
export const createEmployee = implementation.createEmployee;
export const updateEmployee = implementation.updateEmployee;
export const resetEmployeeCode = implementation.resetEmployeeCode;
export const listCategories = implementation.listCategories;
export const createCategory = implementation.createCategory;
export const updateCategory = implementation.updateCategory;
export const deleteCategory = implementation.deleteCategory;
export const listProducts = implementation.listProducts;
export const listInventoryMovements = implementation.listInventoryMovements;
export const transferInventory = implementation.transferInventory;
export const listInstallments = implementation.listInstallments;
export const adjustInventory = implementation.adjustInventory;
export const listCustomers = implementation.listCustomers;
export const listSuppliers = implementation.listSuppliers;
export const listExpenses = implementation.listExpenses;
export const listSales = implementation.listSales;
export const getSalesByEmployee = implementation.getSalesByEmployee;
export const getSaleDetails = implementation.getSaleDetails;
export const listPurchaseItems = implementation.listPurchaseItems;
export const updatePurchaseItem = implementation.updatePurchaseItem;
export const deletePurchaseItem = implementation.deletePurchaseItem;
export const createProduct = implementation.createProduct;
export const createCustomer = implementation.createCustomer;
export const createSupplier = implementation.createSupplier;
export const createExpense = implementation.createExpense;
export const updateProduct = implementation.updateProduct;
export const deleteProduct = implementation.deleteProduct;
export const updateCustomer = implementation.updateCustomer;
export const deleteCustomer = implementation.deleteCustomer;
export const updateSupplier = implementation.updateSupplier;
export const deleteSupplier = implementation.deleteSupplier;
export const deleteExpense = implementation.deleteExpense;
export const recordSyncOperations = implementation.recordSyncOperations;
export const getDailySummary = implementation.getDailySummary;
export const getReportSummary = implementation.getReportSummary;
export const createSale = implementation.createSale;
export const createPurchase = implementation.createPurchase;
export const recordInstallmentPayment = implementation.recordInstallmentPayment;
export const getLocalAuthStatus = localDb.getLocalAuthStatus;
export const createLocalManager = localDb.createLocalManager;
export const loginLocalManager = localDb.loginLocalManager;
export const loginLocalEmployee = localDb.loginLocalEmployee;
export const verifyLocalManagerPassword = localDb.verifyLocalManagerPassword;
export const getLocalUserBySession = localDb.getLocalUserBySession;
export const deleteLocalSession = localDb.deleteLocalSession;
export const logoutLocalUser = localDb.logoutLocalUser;
export const listLocalAuthEvents = localDb.listLocalAuthEvents;
