import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(process.cwd());
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8");

describe("Windows desktop packaging", () => {
  it("includes the Hawr icon and optional signing configuration", () => {
    const packageJson = JSON.parse(read("package.json"));
    const workflow = read(".github/workflows/windows-desktop.yml");
    expect(packageJson.version).toBe("1.5.0");
    expect(packageJson.build.icon).toBe("assets/hawr-icon.ico");
    expect(packageJson.build.publish.provider).toBe("github");
    expect(packageJson.build.publish.repo).toBe("hawr-sales-system");
    expect(packageJson.build.nsis.deleteAppDataOnUninstall).toBe(true);
    const installer = read("electron/installer.nsh");
    expect(installer).toContain('RMDir /r "$APPDATA\\hawr-sales-system"');
    expect(installer).toContain('RMDir /r "$LOCALAPPDATA\\hawr-sales-system"');
    expect(installer).toContain("Hawr Gallery Daily Backup");
    expect(installer).toContain("--daily-backup");
    expect(installer).toContain("schtasks /Delete");
    expect(fs.existsSync(path.join(root, "assets/hawr-icon.ico"))).toBe(true);
    expect(fs.existsSync(path.join(root, "electron/loading.html"))).toBe(true);
    expect(workflow).toContain("WIN_CSC_LINK");
    expect(workflow).toContain("WIN_CSC_KEY_PASSWORD");
    expect(workflow).toContain("electron-builder --win --x64 --publish always");
    expect(fs.existsSync(path.join(root, "electron/installer.nsh"))).toBe(true);
  });

  it("uses the server SQLite status as the first-run source of truth", () => {
    const gate = read("client/src/components/LocalAuthGate.tsx");
    expect(gate).toContain("Treat the server's SQLite status as the single source of truth");
    expect(gate).toContain("if (!status.data?.configured) return <ManagerSetup");
    expect(gate).not.toContain("!status.data?.configured || desktopConfigured === false");
  });

  it("contains a first-run wizard and secure LAN pairing route", () => {
    const main = read("electron/main.cjs");
    const setup = read("electron/setup.html");
    const server = read("server/_core/index.ts");
    const desktopServer = read("server/desktop-server.ts");
    expect(setup).toContain("completeSetup");
    expect(main).toContain("setupComplete");
    expect(main).toContain("/__desktop/pair");
    expect(main).toContain('loadFile(path.join(__dirname, "loading.html"))');
    expect(main).toContain("showStartupError");
    expect(read("electron/loading.html")).toContain("جارٍ تشغيل النظام المحلي");
    expect(main).toContain("mainWindow.show()");
    expect(main).toContain("autoUpdater.autoDownload = true");
    expect(main).toContain("desktop-update-status");
    expect(main).toContain("desktop-network-info");
    expect(main).toContain("desktop-local-setup-state");
    expect(main).toContain("desktop-backup-database");
    expect(main).toContain("desktop-restore-database");
    expect(main).toContain("desktop-reset-database");
    expect(main).toContain("desktop-automatic-backup-status");
    expect(main).toContain("runAutomaticBackup");
    expect(main).toContain("isDailyBackupInvocation");
    expect(read("electron/preload.cjs")).toContain("getAutomaticBackupStatus");
    expect(read("client/src/electron.d.ts")).toContain("getAutomaticBackupStatus?");
    expect(read("client/src/pages/Home.tsx")).toContain("النسخ التلقائي اليومي مفعّل");
    expect(main).toContain("const backup = await backupDatabase()");
    expect(main).toContain("app.relaunch()");
    expect(main).toContain("async function launch() { await createMainWindow(); }");
    expect(main).not.toContain("if (!readSettings().setupComplete) createSetupWindow()");
    expect(main).toContain("isSQLiteDatabase");
    expect(read("electron/preload.cjs")).toContain("backupDatabase");
    expect(read("electron/preload.cjs")).toContain("restoreDatabase");
    expect(read("electron/preload.cjs")).toContain("resetDatabase");
    expect(read("client/src/electron.d.ts")).toContain("resetDatabase?");
    expect(read("client/src/pages/Home.tsx")).toContain("إعادة ضبط النظام والبدء من جديد");
    expect(main).toContain('dist", "desktop-server.js');
    expect(desktopServer).toContain("startDesktopServer");
    expect(desktopServer).toContain("/__desktop/health");
    expect(desktopServer).toContain("options.port");
    expect(read("server/_core/context.ts")).toContain("LOCAL_SESSION_COOKIE");
    expect(read("server/localAuthCrypto.ts")).toContain("timingSafeEqual");
    const routers = read("server/routers.ts");
    expect(routers).toContain("adjust: adminProcedure");
    expect(routers).toContain("transfer: adminProcedure");
    expect(routers).toContain("createProduct: adminProcedure");
    expect(routers).toContain("updateProduct: adminProcedure");
    expect(routers).toContain("deleteProduct: adminProcedure");
    expect(routers).toContain("create: adminProcedure.input(z.object({ invoiceNo");
    expect(desktopServer).toContain('import { serveStatic } from "./_core/static"');
    expect(desktopServer).not.toContain('from "vite"');
    expect(server).toContain("hawr_pair=approved");
    expect(server).toContain("يلزم فتح رابط الربط");
    expect(server).toContain('import { serveStatic } from "./static"');
    expect(server).toContain('const { setupVite } = await import("./vite")');
  });
});
