import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { enqueueOperation } from "../../../shared/offline";
import { findProductByCode, netLineTotal } from "../../../shared/invoice";
import { BarcodeScanner } from "@/components/BarcodeScanner";
import { printReceipt80mm, saveLastReceipt } from "@/lib/receipt";

type Product = { id: number; name: string; sku: string; barcode?: string | null; salePrice: string; costPrice?: string | null; stockQty: number };
type Line = Product & { quantity: number; unitPrice: string; discount: number };

export function InvoiceForm({ mode, products, onSaved }: { mode: "sale" | "purchase"; products: Product[]; onSaved: () => void }) {
  const [invoiceNo, setInvoiceNo] = useState(() => `${mode === "sale" ? "S" : "P"}-${Date.now()}`);
  const [barcode, setBarcode] = useState("");
  const [paidAmount, setPaidAmount] = useState("0");
  const [paymentMethod, setPaymentMethod] = useState<"cash" | "card" | "transfer" | "installment">("cash");
  const [lines, setLines] = useState<Line[]>([]);
  const [scannerOpen, setScannerOpen] = useState(false);
  const sale = trpc.sales.create.useMutation();
  const purchase = trpc.purchases.create.useMutation();
  const trpcUtils = trpc.useUtils();
  const found = useMemo(() => { return findProductByCode(products, barcode); }, [barcode, products]);
  const total = lines.reduce((sum, line) => sum + netLineTotal(Number(line.unitPrice), line.quantity, line.discount), 0);
  const addProduct = () => { if (!found) return; setLines(previous => { const existing = previous.find(line => line.id === found.id); return existing ? previous.map(line => line.id === found.id ? { ...line, quantity: line.quantity + 1 } : line) : [...previous, { ...found, quantity: 1, unitPrice: mode === "purchase" ? (found.costPrice || found.salePrice) : found.salePrice, discount: 0 }]; }); setBarcode(""); };
  const submit = () => { if (!lines.length) return; const input = { invoiceNo, paidAmount, items: lines.map(line => ({ productId: line.id, quantity: line.quantity, unitPrice: Math.max(0, Number(line.unitPrice) - line.discount / line.quantity).toFixed(2) })) }; const onSuccess = () => { saveLastReceipt({ invoiceNo, mode, lines, total, paid: Number(paidAmount) || 0 }); enqueueOperation(mode === "sale" ? "sales" : "purchases", input); void trpcUtils.catalog.products.invalidate(); void trpcUtils.reports.summary.invalidate(); onSaved(); }; if (mode === "sale") sale.mutate({ ...input, paymentMethod }, { onSuccess }); else purchase.mutate(input, { onSuccess }); };
  return <div className="border-2 border-slate-950 bg-white p-5 space-y-5">
    <div className="grid md:grid-cols-3 gap-3"><label className="text-xs font-bold">رقم الفاتورة<Input value={invoiceNo} onChange={e => setInvoiceNo(e.target.value)} className="rounded-none mt-2" /></label><label className="text-xs font-bold md:col-span-2">بحث بالباركود أو SKU<div className="flex gap-2 mt-2"><Input autoFocus value={barcode} onChange={e => setBarcode(e.target.value)} onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); addProduct(); } }} placeholder="امسح الباركود ثم اضغط Enter" className="rounded-none"/><Button type="button" onClick={addProduct} disabled={!found} className="rounded-none bg-red-600">إضافة</Button><Button type="button" onClick={() => setScannerOpen(open => !open)} variant="outline" className="rounded-none">{scannerOpen ? "إخفاء الكاميرا" : "كاميرا"}</Button></div>{barcode && !found && <span className="text-xs text-red-600 mt-1 block">لم يتم العثور على منتج بهذا الرمز</span>}{found && <span className="text-xs text-green-600 mt-1 block">مطابق: {found.name} — المتاح {found.stockQty}</span>}</label>{scannerOpen && <BarcodeScanner onDetected={code => { setBarcode(code); setScannerOpen(false); }} onClose={() => setScannerOpen(false)} />}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">المنتج</th><th className="p-3 text-right">{mode === "purchase" ? "تكلفة الوحدة" : "السعر"}</th><th className="p-3 text-right">الكمية</th><th className="p-3 text-right">الخصم</th><th className="p-3 text-right">الإجمالي</th><th/></tr></thead><tbody className="divide-y divide-slate-100">{lines.map(line => <tr key={line.id}><td className="p-3 font-bold">{line.name}<span className="block text-xs text-slate-400">{line.barcode || line.sku}</span></td><td className="p-3"><Input type="number" min={0} value={line.unitPrice} onChange={e => setLines(all => all.map(item => item.id === line.id ? { ...item, unitPrice: e.target.value } : item))} className="w-28 rounded-none" /></td><td className="p-3"><Input type="number" min={1} max={mode === "sale" ? line.stockQty : undefined} value={line.quantity} onChange={e => setLines(all => all.map(item => item.id === line.id ? { ...item, quantity: Math.max(1, Number(e.target.value)) } : item))} className="w-24 rounded-none" /></td><td className="p-3"><Input type="number" min={0} value={line.discount} onChange={e => setLines(all => all.map(item => item.id === line.id ? { ...item, discount: Math.max(0, Number(e.target.value)) } : item))} className="w-24 rounded-none" /></td><td className="p-3 font-bold">{netLineTotal(Number(line.unitPrice), line.quantity, line.discount).toLocaleString("ar-EG")} ج.م</td><td className="p-3"><button onClick={() => setLines(all => all.filter(item => item.id !== line.id))} className="text-red-600 font-bold">حذف</button></td></tr>)}</tbody></table>{!lines.length && <p className="py-10 text-center text-sm text-slate-400">ابدأ بمسح باركود المنتج لإضافته إلى الفاتورة.</p>}</div>
    <div className="flex flex-col md:flex-row md:items-end gap-4 justify-between border-t border-slate-200 pt-5"><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">المدفوع<Input value={paidAmount} onChange={e => setPaidAmount(e.target.value)} inputMode="decimal" className="rounded-none mt-2" /></label>{mode === "sale" && <label className="text-xs font-bold">طريقة الدفع<select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value as typeof paymentMethod)} className="h-10 mt-2 w-full border border-slate-300 bg-white px-3 text-sm"><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="transfer">تحويل</option><option value="installment">تقسيط</option></select></label>}</div><div className="text-right"><p className="text-xs text-slate-500">إجمالي الفاتورة</p><p className="text-3xl font-black">{total.toLocaleString("ar-EG")} ج.م</p><p className="text-xs text-slate-400 mt-1">المتبقي: {Math.max(0, total - Number(paidAmount)).toLocaleString("ar-EG")} ج.م</p><div className="flex flex-wrap gap-2 mt-4"><Button onClick={submit} disabled={!lines.length || sale.isPending || purchase.isPending} className="rounded-none bg-slate-950">حفظ الفاتورة</Button><Button type="button" variant="outline" disabled={!lines.length} onClick={() => printReceipt80mm({ invoiceNo, mode, lines, total, paid: Number(paidAmount) || 0 })} className="rounded-none">طباعة إيصال 80mm</Button></div></div></div>
  </div>;
}
